### PR TITLE
Nvidia ex line map

### PR DESCRIPTION
**Pull request by jmellorcrummey**
draft pull request to document changes to interpret inlining information embedded in enhanced line maps in CUDA binaries

### CODE REVIEW

**Comment by mxz297** [comment]
@hainest You ignore this PR for the moment as elfutils developers have some change requests for our elfutils patches, which will cause some small changes to this PR. I think it is better to wait until our elftuils patches are finalize.

**Comment by hainest** [comment]
@mxz297 Not a problem. Let me know once things are finalized.

**Comment by mxz297** [comment]
@hainest Based on today's discussion, i think it will be good to test this PR for regression as usual.

**Comment by jmellorcrummey** [comment]
The new elfutils support is available at https://github.com/jmellorcrummey/elfutils.

The support is in the nvidia-inline branch, which is now the default branch.

**Comment by hainest** [comment]
https://bottle.cs.wisc.edu/search?dyninst_branch=PR1093

No regressions with regular elfutils (0.182, I think). I'm still working on the container to run the test suite with John's modified elfutils.

**Comment by mxz297** [comment]
@hainest I rebased this PR and add the cmake test for libdw.

Can you test this PR to see if there is any regression? Meanwhile, I will wait for elfutils 0.186 to be released to a separate end-to-end testing with HPCToolkit.

**Comment by hainest** [comment]
I was planning to release 12.0 tomorrow, but I'd rather have this in the release. Do you think they'll have 0.186 out before next week?

**Comment by mxz297** [comment]
@hainest 0.186 was tagged a few minutes ago. I will do the testing today. So it is still likely for you to do 12.0 release tomorrow.

**Review by hainest — APPROVED** [review]

**Comment by hainest** [comment]
Great! I'm running the usual tests now.

**Comment by mxz297** [comment]
@hainest My test looks good. You can merge this if there is no regression on your end.

**Comment by hainest** [comment]
https://bottle.cs.wisc.edu/search?dyninst_branch=PR1093&since_date=2021-11-08

Looks good. That noise on zeroah is unrelated.

**Comment by hainest** [comment]
@mxz297 Do you want to preserve the history of this branch? If so, would you rather have it as a merge commit or as a rebase-and-merge?

**Comment by mxz297** [comment]
@hainest It would be good to preserve the history of this branch. I rebased this branch on master today, so either merging commit or rebase-and-merge should be trivial.

**Pull request merged**
