### PR TITLE
Recover from a bad force push.

### PR DESCRIPTION
**Pull request by wrwilliams**
Also drags in ppc32/ppc64 WIP, which is not stable; will be fixed or reverted soon.

### CODE REVIEW

**Comment by cuviper** [comment]
Looks like `v9.1.x` was also force-pushed.  For posterity, I got these updates:

    + 910235903207...629eb4d99805 master     -> origin/master  (forced update)
    + df6d090061ba...19281e11a163 v9.1.x     -> origin/v9.1.x  (forced update)

So my master had the same merge of #13 as you, then also the merge of #39.

**Comment by cuviper** [comment]
Commit 910235903207 is also the most recent master build in travis, so I think that's truly the latest.  And in case you hadn't grabbed that one, GitHub is still hotlinking that commit fine, so it should still be possible for you to get it.

    git pull https://github.com/dyninst/dyninst 910235903207341ec1dc00ca86580eaacd683c1a

**Comment by cuviper** [comment]
I can make this easy and just push my `master` and `v9.1.x` back out, if you like.

**Comment by wrwilliams** [comment]
I should have that commit already in my master; I updated my local this morning and it's 2 commits ahead of where we were--and those commits should head to 9.2 anyway.

I'll guard master against this sort of problem; do you mind restoring 9.1.x to where it ought to be?

**Comment by cuviper** [comment]
OK, `v9.1.x` is back to df6d090061ba.

**Comment by wrwilliams** [comment]
And the travis build looks good, so I'm recreating the last two months of master with this.

**Comment by pefoley2** [comment]
Github has a "protect branch" option which prevents force pushes and can optionally require the travis build to pass before PRs can be merged, see https://help.github.com/articles/about-protected-branches/

**Comment by pefoley2** [comment]
It looks like https://github.com/dyninst/dyninst/pull/39 is no longer in master.

**Comment by wrwilliams** [comment]
Master and the release branches are now properly protected; they're not requiring travis to pass yet but that will happen soon. I'll remerge #39.

**Comment by wrwilliams** [comment]
...or not; I guess I can't reopen that. Josh, feel free to resend/push.

**Comment by cuviper** [comment]
See #43

**Pull request merged**
