### PR TITLE
Memory leak fixes

### PR DESCRIPTION
**Pull request by wrwilliams**

### CODE REVIEW

**Comment by wrwilliams** [comment]
retest this please

**Comment by pefoley2** [comment]
Have you considered using std::unique_ptr<> internally since dyninst requires c++11 to build now?

**Comment by wrwilliams** [comment]
Updated test suite with a more stable XML outputter and some testsuite-side bug fixes. Retest this please.

**Comment by wrwilliams** [comment]
retest this please

**Comment by wrwilliams** [comment]
Cleaned zombies from Jenkins; retest this please

**Comment by hainest** [comment]
I will work on getting this rebased onto 10.1.

**Comment by hainest** [comment]
All relevant changes have been converted to new PRs.

**Pull request closed without merging**
