### PR TITLE
Displacement validation checks updated

### LINKED ISSUE #311: BPatch_binaryEdit::writeFile() fails for stack diversification
Starting at commit 31fcb133, BPatch_binaryEdit::writeFile() returns false and fails to instrument with StackMods when using stack diversification.  Probing further reveals that writeFile() is returning false because AddressSpace::patch() is returning false.

Note that the problematic commit originally fixed #111, so we wouldn't want to just revert it.  It is also possible that the problem originated with earlier changes to codegen-x86.C but was hidden by issue #111 until this commit.

**Steps to reproduce**
Needed files:

- Everything in /p/paradyn/development/mm/projects/performStackMods
- Everything in /p/paradyn/development/mm/projects/utils
- /p/paradyn/development/mm/projects/bashrc

How to compile:

1. Copy necessary folders/files to your own machine.  Keep the relative locations of the performStackMods folder and the utils folder the same.
2. Modify bashrc to point DYNINST_ROOT to your Dyninst install directory and TOOLS_ROOT to the directory containing the performStackMods and utils folders.
3. Execute `. bashrc`
4. Run `make clean && make` inside utils/getExecutableProcedures, utils/getFunction, and performStackMods/

How to run:
`./performStackMods -b tonto-orig -o tonto-rewrite -v -d`

### PR DESCRIPTION
**Pull request by jdetter**
Fixes #311. There wasn't anything wrong with the displacement modification code except for the validation checks.

### CODE REVIEW

**Comment by jdetter** [comment]
@wrwilliams Are we doing a 9.4.0 release or will 10.0.0 be the next release version?

**Comment by wrwilliams** [comment]
I think 10.0.0 is the next major release, though we'll almost certainly be pushing patches to 9.3 as well.

**Comment by morehouse** [comment]
This fixes the rewrite error.  I'm having issues with unsafe modifications being made now, but that may be a problem in StackMod.  I'm looking into this at the moment

**Comment by jdetter** [comment]
@wrwilliams good to merge?

**Pull request merged**
