### PR TITLE
Decoding and instructionAPI fixes for x86 (In Progress)

### PR DESCRIPTION
**Pull request by jdetter**
Multiple fixes for #372.

This PR is in progress, not ready for merge.

### CODE REVIEW

**Comment by jdetter** [comment]
@wrwilliams and @mxz297 it looks like there are a ton of testsuite failures on the `att_syntax` branch, would you rather I fix these issues on `master` or do you want them on `att_syntax?`

Here is what I get from the testsuite on x86_64 Fedora:
https://gist.github.com/jdetter/70f11b856f1f7257055127b767d3c4ef

**Comment by mxz297** [comment]
@jdetter @wrwilliams I would say fixing this issue on att_syntax because this decoding issue is not visible on master. 

In terms of the testsuite failures on att_syntax, I think you can focus on fixing this decoding issue. Because this decoding issue will prevent ParseAPI correctly identify jump tables, it could have unexpected impacts on the testsuites.

**Comment by jdetter** [comment]
@mxz297 This now contains a fix for the AVX-512 version of  `vcvtsi2sd` that you requested.

**Comment by jdetter** [comment]
@mxz297 @wrwilliams I'm having a lot of issues reproducing the rest of the issues that aren't fixed, not sure if they were produced with a build that wasn't up to date or what.

Also I am unable to get the most up to date version of Fleece to compile, has that project been reassigned to a new member of the dyninst team or does it not have a maintainer anymore?

**Comment by wrwilliams** [comment]
Fleece doesn't have an active maintainer, though you can ping @nathanhjay with questions.

It's certainly possible that at least some of the instruction decoding issues in the bug database got fixed but not closed; these should be deterministic, so if you can verify that they're resolved, feel free to mark fixed/invalid as the case may be.

**Comment by mxz297** [comment]
@jdetter  I tried your latest changes and they do indeed the reported decoding errors seem fixed. Unfortunately, there is still at least one more decoding error. 
Instructions like 
```
  561c34:       48 89 54 24 20          mov    %rdx,0x20(%rsp)
  561c39:       48 89 44 24 18          mov    %rax,0x18(%rsp)

```
are decoded as:
```
561c34 : mov %rdx,(%rsp)
561c34 : mov %rdx,(%rsp)
```

It seems to me that somehow the displacements are left out. Do you have additional time to fix this? Hopefully, this will be an easy one.

**Comment by mxz297** [comment]
@jdetter No need to worry about the missing displacement decoding issue. It turned out to be not hard to be fixed.

**Comment by jdetter** [comment]
@mxz297 Did you push the fix to `att_syntax`?

**Comment by mxz297** [comment]
@jdetter No. I am on the course of merging my jump table branch, the att_syntax branch, and the arm semantics branch. After I get these all these merges working well for my jump table tests, I merge it with the master. And then I will delete att_syntax and arm semantics since all the work from these two branches are merged.

**Comment by jdetter** [comment]
@mxz297 Ok that works for me

**Comment by mxz297** [comment]
Closed by #401

**Pull request closed without merging**
