### PR TITLE
findMain improvements

### PR DESCRIPTION
**Pull request by jdetter**
Less false positives on `findMain` dataflowAPI analysis. `findMain` now returns an int (0 on success, -1 on failure) instead of void. Some asserts have been taken out and replaced with return -1 (mutatee issues, not internal issues).

### CODE REVIEW

**Comment by jdetter** [comment]
@wrwilliams can this be merged? This doesn't fix the issue on RHEL 6 but it is an improvement on the patch that fixed the issue on Fedora 23 and Ubuntu.

**Comment by wrwilliams** [comment]
Can one of the admins verify this patch?

**Comment by wrwilliams** [comment]
Resubmitting to Jenkins.

**Comment by jdetter** [comment]
@wrwilliams `dyninst-build` is passing but the PR status isn't getting set. It ends with:

```
Finished: SUCCESS
```

**Comment by jdetter** [comment]
Jenkins in complaining because `test_pt_ls` isn't passing, but we already know `test_pt_ls` has issues on RHEL 6

**Pull request merged**
