### PR TITLE
In DwarfWalker, start a new context dissociated from the current context

### PR DESCRIPTION
**Pull request by sashanicolas**
when a dwarf type entry, not yet parsed, is encountered.

### CODE REVIEW

**Comment by mxz297** [comment]
@sashanicolas I have tested this PR locally. It indeed fixes the hang issue during DWARF parsing.

@hainest Ready to test.

**Comment by mxz297** [comment]
@sashanicolas Have you run the test suite on all architectures before merging it?

**Comment by hainest** [comment]
https://bottle.cs.wisc.edu/search?dyninst_branch=PR1013

@mxz297 LGTM.

**Comment by sashanicolas** [comment]
All platforms, three x86_64 machines.

**Comment by mxz297** [comment]
@hainest @sashanicolas Great! Thanks!

**Pull request merged**
