### PR TITLE
Rewrite ABI class

### PR DESCRIPTION
**Pull request by hainest**
This makes it much easier to understand what is actually happening and corresponds to the concepts in the respective ABI standards.

### CODE REVIEW

**Comment by hainest** [comment]
No test regressions.

**Review by kupsch — COMMENTED** [review]
I would suggest changes to these variable names. They are names from the point of view of liveness analysis and would be easier to grasp if they were all from the point of view of the function.  Something like the following and a corresponding `syscall*` set.

Variables:

- `callParamRegs` - registers used to pass parameters to a function
- `callReturnRegs` - registers used to return parameters from a function
- `callPreservedRegs` - registers whose value is preserved on function return
- `callUnpreservedRegs` - registers that a function may overwrite
- `callGlobalRegs` - registers that act as global variable by the ABI/runtime system that are possibly read & written in the function and are valid after a function such as `%rsp`, `%rip` and `%fs`. This makes it so liveness and other analysis has correct values for these registers as these registers are always live/defined/...  

Invariants:

- `callPreservedRegs == ~callUnpreservedRegs` (one should be defined in terms of the other)
- `callReturnRegs & CallUnpreservedRegs == callReturnRegs` (return regs are all unpreserved)

Function return values:

- `getCallReadRegisters` returns `callParams | globalRegs` (registers that may contain meaningful values to the function)
- `getCallWrittenRegisters` returns `callUnpreservedRegs | globalRegs` (registers that a function may overwrite)
- `getReturnReadRegisters` returns `callReturnRegs | callPreservedRegs | globalRegs` (registers that may have a meaningful value after a function returns)
- `getCallParameterRegisters` return `callParamRegs`
- `getReturnRegisters` returns `callReturnRegs`

**Comment by hainest** [comment]
>     * `callPreservedRegs` - registers whose value is preserved on function return

All of the ABI docs refer to these as callee-saved, so I think we should use that label for consistency.

>     * `callUnpreservedRegs` - registers that a function may overwrite

Since this is invariant to ~callUnpreservedRegs, I didn't list it explicitly.

**Comment by hainest** [comment]
Subsumed by #1712.

**Pull request closed without merging**
