### PR TITLE
Attempts to fix legacy test failures in Dyninst test suite

### PR DESCRIPTION
**Pull request by mxz297**
This PR attempts to fix test failures listed in #550.

### CODE REVIEW

**Comment by mxz297** [comment]
test1_22 failures in rewriter mode is fixed.

**Comment by mxz297** [comment]
pc_tls failures should be fixed with this branch and a new commit pushed to the test suite

**Comment by mxz297** [comment]
test_pt_ls failed due to the directory layout change of dyninst installation.

**Comment by mxz297** [comment]
power_decode failed due to recycled & updated opcodes (in other words, the test was wrong).

**Comment by mxz297** [comment]
@hainest Can you pull the current test suite and this branch and give it a run on your machine?  Now there should be no test failures at all on x86-64.

**Comment by hainest** [comment]
@mxz297 When you get a chance, could you rebase this on master?

**Comment by mxz297** [comment]
@hainest rebased.

**Pull request merged**
