### PR TITLE
Fix errors when thread disappears during attach

### PR DESCRIPTION
**Pull request by mplegendre**
Fixes one of the issues reported in #208 

If a thread exited at the wrong point in the middle of attach PC would throw errors where it should have handled it gracefully.

### CODE REVIEW

**Comment by mplegendre** [comment]
I respectfully disagree.  Stylistically I prefer to have the functional code be straight-line, and the error-handling code be indented away under conditions.  The 'if success do work' style leads to long indention chains in the extreme cases.

**Comment by cuviper** [comment]
Regardless of style choice... I tried the patch out and confirmed that it does fix the outright failure to attach in my #208 testcase.  Thanks!

**Comment by cuviper** [comment]
In defense of the "if success do work" style, it can make cleanup easier as you leave each nested level, rather than having to repeat cleanup in each early break/continue/return or use goto-fail cleanup.  Alternatively, RAII cleanup deals with either style well.

**Comment by wrwilliams** [comment]
Quick comments:

RAII is an ideal that I would like Dyninst to move towards when we touch the codebase. Improves encapsulation, improves error handling, just generally a good thing. I won't force it but consider this a nudge that code should trend in that direction.

WRT this patch in particular: if a small patch requires active thought from me before I understand it, it needs revision either in the form of documentation or in the form of improved clarity. This took a couple minutes for me. Your call whether to comment or revise.

**Comment by mplegendre** [comment]
Feel free to fix this is a more stylistically acceptable way.

**Pull request closed without merging**
