### PR TITLE
Support 32-bit builds in Jenkins

### PR DESCRIPTION
**Pull request by cuviper**
Jenkins now has a `dyninst-build32` target using `CFLAGS=-m32`, but it needs this cmake fix to pass the flags to external projects.  I also cherry-picked the `Address`/`Offset` change from `v9.3.x`.

### CODE REVIEW

**Comment by cuviper** [comment]
Hmm, I don't think I have the new triggers set correctly, but you can see the last result here:
http://jenkins.dyninst.org/jenkins/job/dyninst-build32/15/

**Comment by wrwilliams** [comment]
@cuviper I've been tweaking Jenkins flow a bit:

* Builds need to be in series though 2 test jobs can execute in parallel, or we run out of memory and crash Jenkins. I should be able to convince the VM to actually use virtual memory and not just the 4GB physical, but that's our current limiting resource. So I've got build32 downstream of build.
* Aggregating test results works if upstream triggers downstream but not if downstream watches upstream, so building tests is now triggered from build.
* Setting status should come from the PRB or from the commit status setter, not both.

**Comment by wrwilliams** [comment]
And Jenkins should now have 16GB swap, which should make life a good bit more reasonable.

**Comment by cuviper** [comment]
OK, do you need me to do anything more?

**Comment by wrwilliams** [comment]
Don't think so. I'll let you know if I need a hand.

**Comment by wrwilliams** [comment]
retest this please

**Comment by wrwilliams** [comment]
retest this please

**Comment by wrwilliams** [comment]
Fixes #352

**Pull request merged**
