### PR TITLE
Improved the findMain analysis significantly

### PR DESCRIPTION
**Pull request by jdetter**
The `findMain` analysis should be more accurate and less susceptible to asserts and failures. I don't have the 32 bit libraries installed on my workstation but it looked like the 64 bit tests were passing when the testsuite completed.

@wrwilliams ok to test?

### CODE REVIEW

**Comment by jdetter** [comment]
Resubmitted to jenkins

**Comment by jdetter** [comment]
ok to test

**Comment by jdetter** [comment]
@wrwilliams Can you force this to run on jenkins? I'm not sure why the build isn't triggering.

**Comment by wrwilliams** [comment]
add to whitelist

(The commands work for the GHPRB admin list on the job, not the Jenkins admin list. In-house pull requests *should* be whitelisted but clearly something's not quite right there.)

**Comment by wrwilliams** [comment]
Jenkins results look good but they're obviously not updating the PR status right yet. But I think we're clear to merge.

**Comment by jdetter** [comment]
Ok sweet

**Comment by jdetter** [comment]
This will have the same results as before, only commented out code blocks were removed. I'm fine with this being merged whenever.

**Pull request merged**
