### PR TITLE
Fix memory leaks found with lsan

### PR DESCRIPTION
**Pull request by pefoley2**

### CODE REVIEW

**Comment by wrwilliams** [comment]
Ok to test

**Comment by jdetter** [comment]
Created issue #276 for the AppVeyor problem.

**Comment by pefoley2** [comment]
./runTests -all -test test4_2 is passing for me, do you have an example failure?

**Comment by wrwilliams** [comment]
Jenkins appears to have gotten rid of the test results--I need to tell it to keep those around longer. (Jenkins, retest this please.)

**Comment by wrwilliams** [comment]
retest this please

**Comment by pefoley2** [comment]
Is this obsoleted by #317?

**Comment by wrwilliams** [comment]
No, these appear to be entirely orthogonal; #317 mainly targets ensuring that when we destroy a BPatch_addressSpace we get everything it allocated, and the same for when we destroy an image. These commits do look sensible to me, and should be okay to merge.

**Comment by wrwilliams** [comment]
Now that the test infrastructure is updated to produce clean Junit output: retest this please

**Comment by wrwilliams** [comment]
Looks like this may need a rebase, @pefoley2; can you do that when you get a chance?

**Comment by wrwilliams** [comment]
@pefoley2  can you change this to target v9.3.x branch?

**Pull request closed without merging**
