### PR TITLE
Fix test test_reloc 

### LINKED ISSUE #714: test_reloc failing on x86
I'm seeing this on the new [coriander](https://bottle.cs.wisc.edu/details/499) with Kernel 5.0 and glibc-2.29. @xmeng reported failures on [gpu.cs.rice.edu](https://github.com/dyninst/dyninst/pull/638#issuecomment-591657029). I will continue to test.

### PR DESCRIPTION
**Pull request by mxz297**
Fixes #714

@hainest test_reloc regressions are now fixed on gpu.cs.rice.edu. Can you test it on other platforms?

### CODE REVIEW

**Comment by hainest** [comment]
@mxz297 I have a few others in the queue to test, but I'll try to get this in before the end of the week.

@sashanicolas Does this conflict/interact with your relocation fixes?

**Comment by sashanicolas** [comment]
I have not touched those functions.

**Comment by hainest** [comment]
https://bottle.cs.wisc.edu/results/CRASHED/526

test_reloc is still crashing on coriander. NB: That machine has glibc-2.29, so these could be coincidental.

**Comment by mxz297** [comment]
@hainest Rebased against current master.

**Comment by mxz297** [comment]
Closed via #729

**Pull request closed without merging**
