### PR TITLE
Suppress parallelism in dwarf parsing when an alternative debug file 

### PR DESCRIPTION
**Pull request by mxz297**

### CODE REVIEW

**Comment by mxz297** [comment]
@hainest Ready for testing.

**Comment by hainest** [comment]
Have you tested this using Ben's reproducer on the Fedora 33 container?

**Comment by mxz297** [comment]
I tested a few but not all of the reproducer mentioned in Ben's post. I pulled a fedora 33 container locally and can only reproduce the problem on a small subset of the binaries mentioned in Ben's PR. This PR fixed the crashes I saw locally.

**Comment by hainest** [comment]
https://bottle.cs.wisc.edu/search?dyninst_branch=PR929

No new regressions.

**Comment by hainest** [comment]
@mxz297 Based on your testing, should we go ahead and mark this as closing #915, #914, and #913?

**Comment by woodard** [comment]
Can we keep it open for a little bit longer? 
I'll grab the PR929 branch above and I'll retest it then let you guys know the results.

**Comment by hainest** [comment]
@woodard Surely. I ran them on our Fedora 33 container, and the omp crashes went away. However, they are still crashing as in #907, but Sasha is working on that.

**Comment by hainest** [comment]
@woodard Were you able to test this? I'm ready to merge once you are satisfied.

**Comment by hainest** [comment]
@woodard I'm going to merge this in so Sasha can more easily test his fixes. Let us know if your testing finds anything unusual.

**Pull request merged**
