### PR TITLE
Add initial support for decoding AMD FMA4 and XOP instructions

### PR DESCRIPTION
**Pull request by mxz297**
The following FMA4 instructions are supported now:
 e_vfmaddsd, e_vfmaddss, e_vfmsubpd, e_vfmsubsd, e_vfnmaddpd, e_vfnmaddsd,

### CODE REVIEW

**Comment by mxz297** [comment]
XOP instructions support should be added soon,

**Comment by mxz297** [comment]
#573 should be fixed by this PR.

@hainest This PR is ready for testing. The problematic binary compiled on Titan does not have any other missing instructions.

**Comment by mxz297** [comment]
@hainest No regression on Power 8

**Comment by hainest** [comment]
No regressions on ARM (leela) or x86

**Pull request merged**
