### PR TITLE
fix insnCodeGen::modifyData's 64-bit conversion

### PR DESCRIPTION
**Pull request by cuviper**
On RHEL6 with a prelinked `/lib64/libc-2.12.so`, all of tests involving
fork instrumentation were getting SIGSEGV in the mutatee.  This worked
in 9.1, and it also works fine after `prelink -u` to undo libc.  Using
git-bisect found 2b86eb4577bb as the point of regression.

It seems prelink ends up with libc sitting far away from the relocation
buffer, more than a 32-bit displacement, so `insnCodeGen::modifyData`
decides to rewrite that to a 64-bit immediate.  To do this, it has to
emit additional instructions first.  But after the commit above, part of
the rewritten instruction has already been written when we're trying to
emit those extras, and things gets clobbered.

This patch emits those preamble instructions first, before any part of
the newly rewritten instruction is copied out.

### CODE REVIEW

**Comment by jdetter** [comment]
This looks good to me, were you getting this crash on 64 bit x86 or 32 bit?

**Comment by cuviper** [comment]
This was crashing on x86_64.  Isn't this conversion impossible for 32-bit?

**Comment by jdetter** [comment]
Oh yeah, duh

**Comment by cuviper** [comment]
Ok, is there anything to hold this up?  We outsiders can't see what Jenkines is doing on follis...

**Comment by wrwilliams** [comment]
@cuviper Any experience with the AWS-hosted Jenkins here: https://bitnami.com/stacks/developer-tools? An opaque-to-world Jenkins (that also can't properly respond to github) is not the world's most useful CI tool, and I'd certainly rather get it off of my development box...

**Comment by jdetter** [comment]
@wrwilliams I've done a ton of work with AWS in the past if you need any help, especially if it's setting up a Jenkins box

**Comment by cuviper** [comment]
I don't have any experience setting up Jenkins.

Another option is [buildbot](http://buildbot.net/), e.g. my colleague runs this for GDB: http://gdb-build.sergiodj.net/.  I'm not sure where the individual builders are though -- probably still just random development boxes.  I think Rust uses buildbot on AWS, with Homu for GitHub integration -- see [rust-infra](https://github.com/brson/rust-infra).  But again, I haven't run any of these things myself.

**Pull request merged**
