### PR TITLE
update spack.yaml for spack v0.19.1

### LINKED ISSUE #1365: Dockerfile spack.yaml property error
**Intention**
Building Dyninst in docker

**Bug & Reproduce**
```
$ docker build -t dyninst -f Dockerfile ../
[+] Building 196.3s (17/19)                                                                                                             
 => [internal] load build definition from Dockerfile                                                                               0.0s
 => => transferring dockerfile: 37B                                                                                                0.0s
 => [internal] load .dockerignore                                                                                                  0.0s
 => => transferring context: 2B                                                                                                    0.0s
 => [internal] load metadata for docker.io/library/ubuntu:20.04                                                                    0.5s
 => [internal] load build context                                                                                                  0.1s
 => => transferring context: 115.76kB                                                                                              0.1s
 => CACHED [ 1/15] FROM docker.io/library/ubuntu:20.04@sha256:4a45212e9518f35983a976eead0de5eecc555a2f047134e9dd2cfc589076a00d     0.0s
 => [ 2/15] RUN apt-get -qq update &&     apt-get -qq install -fy tzdata &&     apt-get -qq install -y --no-install-recommends   109.5s
 => [ 3/15] RUN python3 -m pip install --upgrade pip &&     python3 -m pip install clingo &&     dpkg-reconfigure tzdata           5.0s
 => [ 4/15] RUN apt-get install -y software-properties-common &&     add-apt-repository -y ppa:ubuntu-toolchain-r/test &&     ap  59.2s 
 => [ 5/15] WORKDIR /opt                                                                                                           0.0s 
 => [ 6/15] RUN git clone --depth 1 https://github.com/spack/spack                                                                 9.3s 
 => [ 7/15] RUN python3 -m pip install botocore boto3                                                                              5.2s 
 => [ 8/15] RUN spack external find --not-buildable gcc autoconf bzip2 git tar xz perl cmake m4 ncurses &&     spack config add '  2.8s
 => [ 9/15] RUN printf "\n  boost:\n    externals:\n    - spec: boost@1.71.0\n      prefix: /usr\n    buildable: false\n  intel-t  0.4s
 => [10/15] WORKDIR /code                                                                                                          0.0s
 => [11/15] COPY . /code                                                                                                           2.6s
 => [12/15] WORKDIR /opt/dyninst-env                                                                                               0.0s
 => ERROR [13/15] RUN . /opt/spack/share/spack/setup-env.sh &&     spack env create -d . &&     echo "  concretization: together"  1.7s
------
 > [13/15] RUN . /opt/spack/share/spack/setup-env.sh &&     spack env create -d . &&     echo "  concretization: together" >> spack.yaml &&     spack env activate . &&     spack add cmake@3.16.3 &&     spack add perl@5.30.0 &&     spack add boost@1.71.0 &&     spack add elfutils@0.186 &&     spack add libiberty@2.33.1+pic &&     spack add intel-tbb@2020.3 &&     spack install --reuse:
#17 1.304 ==> Created environment in /opt/dyninst-env
#17 1.304 ==> You can activate this environment with:
#17 1.304 ==>   spack env activate /opt/dyninst-env
#17 1.629 ==> Error: /opt/dyninst-env/spack.yaml:7: Additional properties are not allowed ('concretization' was unexpected)
------
executor failed running [/bin/sh -c . /opt/spack/share/spack/setup-env.sh &&     spack env create -d . &&     echo "  concretization: together" >> spack.yaml &&     spack env activate . &&     spack add cmake@${CMAKE_VERSION} &&     spack add perl@${PERL_VERSION} &&     spack add boost@${BOOST_VERSION} &&     spack add elfutils@${ELFUTILS_VERSION} &&     spack add libiberty@${LIBIBERTY_VERSION}+pic &&     spack add intel-tbb@${INTELTBB_VERSION} &&     spack install --reuse]: exit code: 1
```

**System (please complete the following information):**
 - platform: Docker version 20.10.17, build 100c701
 - master branch

### PR DESCRIPTION
**Pull request by weixiao-zhan**
https://spack.readthedocs.io/en/v0.19.1/environments.html#spec-concretization

fixes #1365

### CODE REVIEW

**Comment by vsoch** [comment]
It looks like the automated build was disabled - @hainest you might want to test this locally to make sure the new spack builds (can't assume that it does!)

**Comment by hainest** [comment]
@weixiao-zhan How are you building Dyninst that you ran into this? I disabled these builds because I was tired of chasing spack and our rate of change was small enough that local builds were fine.

**Comment by weixiao-zhan** [comment]
Yes, I was rebuilding Dyninst from the latest master branch (I was previously using v12.1.0, and I wanted to make sure the ENDBR patch works with the latest code). As mentioned in issue #1365 , I changed the yaml following their doc. Before spack changes their commands again, this should work.

**Comment by hainest** [comment]
Ok. If it's working for you, then it's fine to merge. If you could 'Squash and Merge' that would be great.

**Pull request merged**
