### PR TITLE
Make dynC work on windows

### PR DESCRIPTION
**Pull request by pefoley2**
Moved to branch for jenkins testing.

### CODE REVIEW

**Comment by pefoley2** [comment]
ok to test

**Comment by pefoley2** [comment]
Odd, it appears to not be picking up the boost libraries.
@wrwilliams thoughts?

**Comment by wrwilliams** [comment]
I've been trying to get automatic boost library downloads working and did a workspace clean; somehow (and I'd dearly love to know how!) that broke the autodetect of what's in /usr/lib/x86_64-linux-gnu. It's on my list of fires to fight today.

**Comment by wrwilliams** [comment]
retest this please

**Comment by pefoley2** [comment]
Friendly ping :)

**Pull request merged**
