### PR TITLE
Fix data races and asserts discovered on Power 

### PR DESCRIPTION
**Pull request by mxz297**
Fix all reported segfault and abort mentioned #1035

### CODE REVIEW

**Comment by mxz297** [comment]
@hainest Ready for testing

**Comment by hainest** [comment]
https://bottle.cs.wisc.edu/regressions?id=12853

This reduced the number of crashes when OMP_NUM_THREADS=16 from 156 to 29. I've left the binaries on llnl.cs.rice.edu under /home/th37/paradyn/seW2KFlA.

**Comment by mxz297** [comment]
@hainest I was able to reproduce the aborts. The asserts in the code indeed represent errors, but they are not necessarily fatal. So I converted them to debug logging. Can you retest?

**Comment by hainest** [comment]
https://bottle.cs.wisc.edu/search?dyninst_branch=PR1038

Looks good on Power9 with 16 OMP threads. I'll re-test on other platforms just to be sure.

**Comment by hainest** [comment]
No regressions on the other platforms.

@mxz297 I'm curious as to why this was only happening on PPC with N>=16 threads, and nowhere else. What sort of conditions would lead a function to be changed from RETURN to NORETURN? Might that decision be a race condition?

**Comment by mxz297** [comment]
@hainest We may see it on arm but arm static rewriting is not enabled anyway. This problem happens when parsing libc.a. The problem is that .a files are not final binaries; they are a collection of .o files. So, calls to other functions from other .o files are not filled. On Power, it will look like:

```
 60:   01 00 00 48     bl      60 <__libc_init_first+0x60>
```

Note that this becomes a function call targeting itself. It will leads to create additional functions and other complication. And yes, in the end, it is a race condition and will lead to inconsistent parsing results. But I don't think I want to tune code parsing for this special case. 

On x86-64, there are also incomplete call instructions:

```
 40:   e8 00 00 00 00          callq  45 <__libc_init_first+0x45>
```

but note that the difference is that on x86, all PC-relative is post-instruction. So this becomes a call to its next instruction, which is like a thunk on 32-bit code for retrieving PC values, and I believe Dyninst has special code for this case.

You may also be interested in why my script does not find this case: my script use `file` command to check if the output includes `ELF`. When you run `file` on a .a file, it says `current ar archive`. So no `ELF`, and .a files are not included...

For Dyninst testing, you may want to change my script to include .a files. Note that hpcstruct does not analyze .a files.

**Comment by hainest** [comment]
That makes sense. I was thinking about it from the perspective of parsing an executable that is linked against a static library, rather than parsing the static library, itself. I agree we don't want special handling for this.

Which script are you referring to?

**Comment by mxz297** [comment]
> That makes sense. I was thinking about it from the perspective of parsing an executable that is linked against a static library, rather than parsing the static library, itself. I agree we don't want special handling for this.
> 
> Which script are you referring to?

The script that I used to crawl binaries under a directory for testing hpcstruct.

**Pull request merged**
