### PR TITLE
Add Clang compiler support

### PR DESCRIPTION
**Pull request by blue42u**
Two minor changes that let Dyninst compile with Clang. Comments and adjustments welcome.

Ping @hainest

### CODE REVIEW

**Comment by hainest** [comment]
@blue42u thanks! It's interesting that the original problem (#497) didn't need to be fixed for Dyninst to build with clang now.

**Comment by blue42u** [comment]
It does need fixed, I just used a different method to do it (casting to `char*` rather than to `uint64_t` and back). I figured this way would be cleaner and more portable.

**Comment by hainest** [comment]
LLVM supports a very limited number of options for the '.machine' directive on PPC ([code](https://github.com/llvm-mirror/llvm/blob/master/lib/Target/PowerPC/AsmParser/PPCAsmParser.cpp#L1705)). This breaks DyninstAPI_RT ([code](https://github.com/dyninst/dyninst/blob/master/dyninstAPI_RT/src/RTthread-powerpc-asm.S#L8)). The fix is just to ignore this directive in RThread-powerpc-asm.S when compiling with clang.

```
#ifndef __clang__
# if defined(arch_64bit)
   .machine "ppc64"       
# else
   .machine "ppc"       
# endif
#endif
```

**Comment by blue42u** [comment]
Folded that new change in (and the equivalent in RTthread-power-asm.s). Untested but should work.

**Comment by hainest** [comment]
Closing to migrate to public Dyninst branch.

**Pull request closed without merging**
