### PR TITLE
Restored dyn_regs.h to v9.2.0 version

### LINKED ISSUE #136: ABI changes from v9.2.0 to v9.2_patches
Just looking at public headers, there are two obvious groups of changes, both from `common/`.  In `dyn_regs.h`, many register variables have been added.  In `entryIDs.h`, a handful of new enum values are added, but since these are added in the middle, they will change all of the values that follow.
[diff-headers-dyninst-v9.2.diff.gz](https://github.com/dyninst/dyninst/files/394528/diff-headers-dyninst-v9.2.diff.gz)

Using [libabigail](http://www.sourceware.org/libabigail/)'s `abipkgdiff`, we can confirm that these are the only real changes, as well as see the function paths where these are exposed.
[abipkgdiff-dyninst-v9.2.log.gz](https://github.com/dyninst/dyninst/files/394527/abipkgdiff-dyninst-v9.2.log.gz)

The plain additions are generally fine for backward compatibility, but not forward.  That is, something which links against the new library may not be able to run with the older library, if it used new symbols.

The existing enum entries which changed their values are a bigger problem, both forward and back.

### PR DESCRIPTION
**Pull request by jdetter**
Fixes #136. Reverts dyn_regs.h to the exact version of v9.2.0.

### CODE REVIEW

**Comment by cuviper** [comment]
Travis will tell, but doesn't dataflowAPI need to stop referencing these too?

**Comment by jdetter** [comment]
I probably should have checked, sorry I'm not used to getting up this early lol

**Comment by jdetter** [comment]
Another patch will be added to this PR, I'm waiting for the compilation to complete.

**Comment by jdetter** [comment]
My testsuite run is still going but so far it looks like it's good. We'll see what Travis says as well.

**Comment by cuviper** [comment]
@jdetter, is there a weaker fix you can put in place for #114?  Just to avoid that out-of-bounds access on `ret.read[getIndex(base)]` where the index is `-1`.  If there's no reasonable action, even an assert would be better than undefined behavior, and that safety net might even be nice for master, in case of future surprises.

**Comment by jdetter** [comment]
There really really should be a check of the return value of `getIndex()` if it's used as an indexer into an array. I can definitely put more checks in there and either return failure or throw an assert.

**Comment by jdetter** [comment]
Asserts added in `liveness.C` where `getIndex` could cause a buffer underread when it's result is used as an indexer for an array.

**Comment by jdetter** [comment]
Is there anything else you think we need to sneak in here?

**Comment by cuviper** [comment]
LGTM

**Pull request merged**
