### PR TITLE
Fixes for AbsRegion and jump table index slicing involving global variable

### LINKED ISSUE #694: `wrong` ip when expanding instruction to assignment ?
```
 41274f:       8b 05 cb 51 28 00       mov    0x2851cb(%rip),%eax        # 697920 <blame_date_mode>
 412755:       ff 24 c5 50 d1 63 00    jmpq   *0x63d150(,%rax,8)
``` 

Hi, When expanding instruction to assignment at `0x41274f`, the log of dyninst shows that the result of ` 0x2851cb(%rip)` equals to `0x69791a`, while the expected value is `0x697920`.

The log of dyninst is shown as below:

```
    slicing from 41274f, currently watching 1 regions
                                        Comparing current [x86_64::rax] to candidate [x86_64::rax]
                                                Match!
                         cached [[x86_64::rax]] -> <(@41274f<[x86_64::rax]>[_69791a]),[x86_64::rax]>
                Expanding instruction @ 41274f: mov 0x2851cb(%rip),%eax, assignment (@41274f<[x86_64::rax]>[_69791a])
``` 
It seems that dyninst may treat `rip` as `0x41274f` not next instruction address `0x412755` when expanding instruction to assignment at address `0x41274f`?

The binary is attached below:

[git_gcc_O2.gz](https://github.com/dyninst/dyninst/files/4079929/git_gcc_O2.gz)

Thanks for your help!

### PR DESCRIPTION
**Pull request by mxz297**
Fixes #694 and #692

### CODE REVIEW

**Comment by mxz297** [comment]
@bin2415 Can you check out my fix and see if these two problems are fixed on your end?

**Comment by bin2415** [comment]
Great! It works on my side, thanks!

**Comment by mxz297** [comment]
@hainest Ready to test and merge.

**Comment by hainest** [comment]
https://bottle.cs.wisc.edu/search?dyninst_branch=PR695&status=OK

Testing well, but I'm having troubles getting it to run successfully on cayenne. I'll try a few more times.

**Comment by hainest** [comment]
`test_reloc` is consistently failing on Cayenne, but it also fails with the head of master.

**Pull request merged**
