### PR TITLE
Partial fix for ABI issues on v9.2_patches

### PR DESCRIPTION
**Pull request by jdetter**
This is a partial fix for #136. I'm not sure if the `entryIDs` issue can be cleanly fixed.

### CODE REVIEW

**Comment by jdetter** [comment]
5a83500 can be cherry picked from this, I accidentally started the patch branch from master instead of v9.2_patches.

**Comment by cuviper** [comment]
I don't understand what you're doing here.  It looks like you just shuffled them around?  How does this address ABI at all?

**Comment by jdetter** [comment]
Idk why the diff looks so weird, but I moved the YMM*, ZMM* and K* register definitions below the older definitions, which should give them larger register numbers, which should give backward compatibility right?

**Comment by cuviper** [comment]
AFAICS `DEF_REGISTER` yields independent values.  I don't think order matters.  The ordering concern was related to the other ABI issue, `enum entryID`, where their values are implicit.

**Comment by jdetter** [comment]
Ah, okay, so I'll delete this PR and then do you want me to revert those two commits I mentioned? Those two commits just added support for a couple of AES instructions that can just go into 9.3.0 instead of 9.2.1.

**Pull request closed without merging**
