### PR TITLE
Memory leak fixes

### PR DESCRIPTION
**Pull request by mxz297**
This PR addresses a subset of the memory leaks identified in #756 .

With this PR, @stanfordcox can finish instrumentation test.

### CODE REVIEW

**Comment by mxz297** [comment]
@hainest I developed this PR based on the libxul_fixes branch because fixes in libxul_fixes are necessary for me to be able to run the instrumentation test. Do you want to me to close that libxul_fixes PR #755 or you want to do incremental testing?

I am fine with either way and I can rebase this PR if you prefer to first test and merge #755.

**Comment by hainest** [comment]
@mxz297 That's fine. I'm nearly done testing #755. Once I merge that, I'll test this one next.

**Comment by mxz297** [comment]
@hainest We can defer the testing of this PR for a few days. I used heaptrack to profile memory usage for DWARF parsing, and found several big memory leaks that worth investigation. I already fixed one memory leak that brings down peak memory usage from 50GB to 40GB when analyzing a 8GB shared library. There are a few more leaks that I want to investigate.

**Comment by hainest** [comment]
@mxz297 Not a problem. Let me know when you're ready.

**Comment by mxz297** [comment]
@hainest We fixed simple leaks and rebased this PR based on current master. Ready for testing.

**Comment by hainest** [comment]
@mxz297 Will this close #756?

**Comment by mxz297** [comment]
This does not address all leaks mentioned in #756, but practically it gets the memory usage problem under control. So practically, this closes #756.

**Comment by hainest** [comment]
https://bottle.cs.wisc.edu/search?dyninst_branch=PR758

This PR is causing many regressions. The most common error is

    Warning: request to instrument loop entry of a loop w/o an entry edge.ERROR: failed to find loop exit points!

**Comment by mxz297** [comment]
@hainest Can you re-test? I deleted some variables that I thought was dead code. I am surprised that it did not cause compilation errors.

**Comment by hainest** [comment]
https://bottle.cs.wisc.edu/search?dyninst_branch=PR758&since_date=2020-06-01

Things are looking much better. I have a couple of more runs to do.

**Comment by hainest** [comment]
Everything looks good. Do you want to preserve the history of the commits?

**Comment by mxz297** [comment]
I am fine with either way.

**Pull request merged**
