### PR TITLE
Implement ARMv8 Rewriter IMFC

### PR DESCRIPTION
**Pull request by LER0ever**
This PR implements the Inter-Module Function Calls for Dyninst Rewriter mode. 

- Currently 28 out of 41 tests of **group 1** pass, (with 8 fail, 5 crash)
- ~~still need to check rewriter mode to prevent regression for dynamic mode~~
- Currently the testsuite cannot run multiple tests, otherwise all of them would fail

The test script I'm using to run individual tests: 
```bash
for i in `seq 1 41`; do ./runTests -rewriter -test test1_$i; done
```

image
image

### CODE REVIEW

**Comment by mxz297** [comment]
@sashanicolas Should this be merged to ARMv8 branch?

**Comment by sashanicolas** [comment]
@mxz297 not yet. @LER0ever was still trying to fix the last tests of group 1.

**Comment by LER0ever** [comment]
> @mxz297 not yet. @LER0ever was still trying to fix the last tests of group 1.

@sashanicolas actually you can merge it. The `test store shared` is not related to the function implemented in this PR, and therefore won't be added to this one.

**Comment by sashanicolas** [comment]
These has been moved to branch https://github.com/dyninst/dyninst/tree/ER/ARMv8.

**Pull request closed without merging**
