### PR TITLE
Cubin

### PR DESCRIPTION
**Pull request by jmellorcrummey**
Changes that make it possible for Dyninst to ingest CUBIN files.

### CODE REVIEW

**Comment by jmellorcrummey** [comment]
I looked at the CI errors reported for my pull request. Appveyor died because some network connection was terminated. Not my fault.

Travis died because it didn't know where the libelf library was. This is completely unrelated to anything I have done and also not my fault

**Comment by wrwilliams** [comment]
ok to test

**Comment by wrwilliams** [comment]
(Jenkins is authoritative for *nix integration, appveyor needs fixing, and travis should get yanked as it's obsolete compared to our Jenkins setup.)

**Comment by jmellorcrummey** [comment]
If you look at the Jenkins log, to me it appears that the failure was a problem with the testing harness not my code:

26417
26418
Cleaning build dir... /opt/bitnami/apps/jenkins/jenkins_home/jobs/dyninst-build/workspace/build
ERROR: Unable to delete '/opt/bitnami/apps/jenkins/jenkins_home/jobs/dyninst-build/workspace/build/.nfs94ab21165825d04a0000b1b5'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
Build step 'CMake Build' marked build as failure
Archiving artifacts
Recording fingerprints



--
John Mellor-Crummey		Professor
Dept of Computer Science	Rice University
email: johnmc@rice.edu		phone: 713-348-5179

**Comment by jmellorcrummey** [comment]
Updated pull request with the following:
1. fixes to Object-elf.C to fix bug in reading of line map
2. add support for debugging ranges associated with functions in modules and inlined functions, which includes definitions associated with PrintPreorder in IBStree.h and wrappers (dumpFuncRanges and dumpModRanges) in Symtab.h to make the inlined definitions available in the debugger
3. merged with dyninst master

**Comment by jmellorcrummey** [comment]
I looked at the build failure with Travis. The reason it failed is that it is using the system version of elf.h. When I installed elfutils-0.170, I had to manually copy elf.h into the include directory. The elf.h included in recent versions of elfutils provides the definition EM_CUDA.

**Comment by jmellorcrummey** [comment]
This pull request is now obsolete. Sasha factored out several pieces, which he already merged into Dyninst. I have refactored the rest into separate pull requests. One piece of this pull request was specifically omitted in my other pull requests: passing a mangledName from Symtab to ParseAPI. This functionality is no longer needed by HPCToolkit after some rewriting.

**Pull request closed without merging**
