### PR TITLE
CMake fixes for Cotie and GCC 4.4 compatibility

### LINKED ISSUE #160: make install not working on latest master
On the latest master, `make install` won't complete on Fedora 23:

```
[detter@localhost dyninst]$ make install
[  0%] Building DyninstRT
[ 25%] Built target dyninstAPI_RT
[ 51%] Built target dyninstAPI_RT_m32
[ 75%] Built target dyninstAPI_RT_m32_static
[100%] Built target dyninstAPI_RT_static
[  0%] Built target DyninstRT
[  9%] Built target common
[ 10%] Built target dynElf
[ 13%] Built target dynDwarf
[ 14%] Built target symLite
[ 18%] Built target instructionAPI
[ 27%] Built target symtabAPI
[ 47%] Built target parseAPI
[ 56%] Built target pcontrol
[ 62%] Built target stackwalk
[ 68%] Built target patchAPI
[ 95%] Built target dyninstAPI
[ 97%] Built target parseThat
[100%] Built target dynC_API
Install the project...
-- Install configuration: "Debug"
CMake Error at dyninstAPI_RT/cmake_install.cmake:44 (file):
  file INSTALL cannot find
  "/home/detter/Workspace/dyninst/dyninstAPI_RT/CMakeFiles/CMakeRelink.dir/libdyninstAPI_RT.so.9.2.0".
Call Stack (most recent call first):
  cmake_install.cmake:36 (include)



Makefile:61: recipe for target 'install' failed
make: *** [install] Error 1
```

### PR DESCRIPTION
**Pull request by jdetter**
This will fix build issues on Follis which will fix most of the Jenkins issues right now. This also includes the make install fix #160 and also the `nullptr` compatibility issue #162.

### CODE REVIEW

**Comment by jdetter** [comment]
Dyninst build finally passing again, `test_pt_ls` is still a work in progress. I didn't have any time to look at it last week because I was working on this. I will be looking at `test_pt_ls` the rest of today and tomorrow.

@wrwilliams and other admins, ok to merge?

**Comment by jdetter** [comment]
I'm actually having weird CMake issues with this after a clean clone/build. I'm not sure why this isn't reflected in the jenkins.

**Comment by cuviper** [comment]
I appreciate the conditional cotire.  Can we also guard this on CMake version?  The `cotire.cmake` mandates 2.8.12, but RHEL7 has only 2.8.11 -- yet a new enough GCC to pass your test.

**Comment by jdetter** [comment]
Yup I can add that as well!

**Comment by jdetter** [comment]
I have tested this on all versions of GCC that the CSL provides. It looks like we need to disable Cotire up to GCC version 4.5.0. Cotire is also disabled if the CMake version isn't at lease 2.8.12.

Cotire also only supports GNU, Intel and Clang compilers on Linux. I didn't mess with changing the Cotire configuration for Windows because it looks like the Cotire support for Windows is pretty good.

This is ready for a merge whenever someone thinks it's ready.

**Comment by jdetter** [comment]
@wrwilliams can this be merged in?

**Comment by wrwilliams** [comment]
Looks clean to me. Any objections/observed regressions from @cuviper?

**Comment by cuviper** [comment]
Works for me.

**Pull request merged**
