### PR TITLE
Remove unnecessary assertion for unknown phdr_type

### PR DESCRIPTION
**Pull request by bbiiggppiigg**
This should fix the problem of failed assertion in EmitELF.C when an unknown phdr_type is seen.

### CODE REVIEW

**Comment by sashanicolas** [comment]
@bbiiggppiigg did you fix the assertion problem?

**Comment by bbiiggppiigg** [comment]
@sashanicolas following your suggestion, I fixed the problem by removing the assertion.
However, as there are unwanted commits associated with this pull request, I'm considering reforking the repo and redo the pull request. 

Do you think this is the right way ?

**Comment by hainest** [comment]
@bbiiggppiigg You don't need to refork. You can just make a new branch. You could also do an interactive rebase (`git rebase -i`) and remove the unwanted commits, then force-push the branch.

**Comment by sashanicolas** [comment]
@bbiiggppiigg did you finish the documentation part? Or was it a lot of work to finish it?
@hainest can't he just revert the unwanted commit and just merge?

**Comment by bbiiggppiigg** [comment]
@sashanicolas 
I thought Bart said I shouldn't change the documentation to latex.
I'll create another branch that separates out the examples only and make a pull request for that.
Since I followed hainest's advice and force-pushed the repo, this pull request can't be re-opened  anymore

**Comment by sashanicolas** [comment]
@bbiiggppiigg ok then

**Pull request closed without merging**
