### PR TITLE
Add xsave instruction

### PR DESCRIPTION
**Pull request by hainest**
@tylergu Could you try this out and see if you can now parse this instruction?

### CODE REVIEW

**Comment by tylergu** [comment]
I tried this pull request but it did not solve the problem. Let me write a simple example to test it to make sure.

**Comment by tylergu** [comment]
I wrote a simple hard-coded example to test this, and the `xsave` instruction is correctly parsed. So this pull request is correct.

The problem was that there is another undefined opcode `xrstor` inside the `_dl_runtime_resolve` blocking the parsing. Could you add this opcode too?

Also along the way of writing this test code, I encountered an assertion when I call ParseAPI::CodeObject::parse(target=function_addr, recursive=false). It does not happen when the recursive flag is true. Should I open an issue for this?

**Review by tylergu — APPROVED** [review]

**Comment by hainest** [comment]
>I wrote a simple hard-coded example to test this, and the xsave instruction is correctly parsed. So this pull request is correct.

>The problem was that there is another undefined opcode xrstor inside the _dl_runtime_resolve blocking the parsing. Could you add this opcode too?

Ah, ok. I'll make a separate PR for that.

>Also along the way of writing this test code, I encountered an assertion when I call ParseAPI::CodeObject::parse(target=function_addr, recursive=false). It does not happen when the recursive flag is true. Should I open an issue for this?

Yes, and please include any binaries, if possible.

**Comment by hainest** [comment]
https://bottle.cs.wisc.edu/search?dyninst_branch=PR1055

No regressions.

**Pull request merged**
