### PR TITLE
DO NOT MERGE: ABI breakage test

### PR DESCRIPTION
**Pull request by hainest**

### CODE REVIEW

**Comment by vsoch** [comment]
ooh this should be fun!

**Comment by vsoch** [comment]
:popcorn: :popcorn: :popcorn:

**Comment by vsoch** [comment]
So @hainest you are saying I should merge this, and right away? :laughing:

**Comment by hainest** [comment]
It compiles, so ship it!

**Comment by vsoch** [comment]
ahh so making ABI errors is hard because they don't even build! A new challenge, lol.

**Comment by hainest** [comment]
It's the same issue as before: the headers in the view are older than what's being compiled in the test container. I'll need to fix that first.

**Comment by hainest** [comment]
Oh, neat. It topologically sorts the jobs and runs as many as it can in parallel.

**Comment by vsoch** [comment]
Ah ok - and just to check this is because of some change you've made here but not the base container yet? This typically should not happen!

**Comment by vsoch** [comment]
> Oh, neat. It topologically sorts the jobs and runs as many as it can in parallel.

Yeah! The only bit of potential "could be faster" bit of that is that it needs to download the _entire_ cache per job just to get one file. If you wanted to speed it up you could create a separate artifact per file, and have the job download it (akin to how we name the cache based on the stage, you'd add the filename you want there and then only save that file to it for each).

I figured the time was trivial compared to the compile and left it as is.

**Comment by hainest** [comment]
Yaaay!

**Pull request closed without merging**
