### PR TITLE
Fixes for test_pt_ls

### PR DESCRIPTION
**Pull request by jdetter**
These changes made it into `v9.2_patches` but didn't make it into master yet.

### CODE REVIEW

**Comment by jdetter** [comment]
@wrwilliams is `dyninst-pr-build` still broken or is that an actual issue?

**Comment by wrwilliams** [comment]
Tests are still running, and I don't think the JUnit outputter is working on this build, but we can manually verify in the worst case.

**Comment by jdetter** [comment]
@wrwilliams Can this be merged? I'm not sure why dyninst-build hasn't finished in 2 days. This fixes #123

**Comment by wrwilliams** [comment]
http://follis.cs.wisc.edu:8080/job/dyninst-test/11/consoleFull (internal access only) has the test results that are relevant; do you expect the failures that are there? They're showing up on a lot of Jenkins builds, so it may be something with the configuration/environment...

**Comment by wrwilliams** [comment]
In any event, if it's on 9.2 patches, it should go to master, so merging.

**Comment by jdetter** [comment]
`test_pt_ls` should definitely be fixed on RHEL 6 and Fedora 23, what distro is follis running?

**Comment by wrwilliams** [comment]
RHEL6.

**Comment by wrwilliams** [comment]
Found the problem, btw: the Jenkins dyninst build step was still using jenkins' own archiving rather than tar, and that strips permissions. So parseThat was -x in the CI system.

I'll look at the rest of these Monday, though if anyone else is bored I won't argue.

**Comment by jdetter** [comment]
Thanks @wrwilliams, it looks like there is another issue with `test_pt_ls` on RHEL 6. Somehow the mutatee is generating a SIGSEGV, however parseThat is returning success...

**Pull request merged**
