### PR TITLE
Fix overlapping bug of program header segments on fixPhdr.

### PR DESCRIPTION
**Pull request by sashanicolas**
This fix is making the update of the program headers in two passes. First,
we need to update the addresses, and then insert the new created segment.

This needs to be tested on all supported platforms on rewriter mode.

### CODE REVIEW

**Comment by hainest** [comment]
Do you remember which test failure triggered this?

**Comment by mxz297** [comment]
@hainest IIRC, this is caused by a rewriter test failure involving rewriting a shared library. The issue fixed by Sasha here however is not sufficient to make that test passing. 

So, from a test suite perspective, we are not going to see any more tests passing. It will be a success if there is no regression.

**Comment by hainest** [comment]
This depends on #614 and #612.

**Comment by sashanicolas** [comment]
@hainest the tests that triggered this involved the shared libraries A and B. This fix is not sufficient as @mxz297  said, but with https://github.com/dyninst/dyninst/pull/612 and https://github.com/dyninst/dyninst/pull/614 it is.

**Comment by hainest** [comment]
https://bottle.cs.wisc.edu/branch/PR618

No regressions.

**Pull request merged**
