### PR TITLE
Fixes for test_pt_ls

### PR DESCRIPTION
**Pull request by jdetter**
`findMain` now uses dataflowAPI to calculate the address of main in a register.

### CODE REVIEW

**Comment by cuviper** [comment]
<meta> Is `v9.2_patches` supposed to be a stable branch for the next `v9.2.1`?  It seems weird that you would push non-trivial commits there without review, then PR it to `master`.

Anyway, I'll try this out on Fedora later today.

**Comment by jdetter** [comment]
Hmm I think we've been treating `v9.2_patches` more as just a staging branch, then doing PR's to keep master up to date with the stable commits. @wrwilliams any input here?

**Comment by cuviper** [comment]
That question is also important for API/ABI tracking.  If there's a branch intended for a 9.2.x point release, it needs to be very careful about compatibility.

**Comment by wrwilliams** [comment]
v9.2_patches is intended to be a stable branch for 9.2.1.

**Comment by jdetter** [comment]
I've found more issues with finding main on small binaries that I would like to take a swing at, I'll add to this when I have more optimizations.

**Pull request closed without merging**
