### PR TITLE
Code cleanup & compiler warning fixes

### LINKED ISSUE #818: Remove VLAs
gcc and clang support `-Wvla`.

### LINKED ISSUE #986: Implicit fallthrough in switch statements
- [x] common/src/arch-x86.C:11434
- [ ] common/src/arch-x86.C:11995
- [ ] dwarf/src/dwarfExprParser.C:337
- [ ] symtabAPI/src/Symtab-edit.C:74
- [ ] symtabAPI/src/parseStab.C:465
- [ ] symtabAPI/src/parseStab.C:1896
- [ ] symtabAPI/src/parseStab.C:1902
- [ ] proccontrol/src/loadLibrary/codegen.C:156
- [ ] proccontrol/src/loadLibrary/codegen.C:175
- [ ] proccontrol/src/linux.C:371
- [ ] proccontrol/src/linux.C:394
- [ ] proccontrol/src/linux.C:652
- [x] patchAPI/src/PatchMgr.C:438
- [ ] stackwalk/src/x86-wanderer.C:108
- [ ] dyninstAPI/src/ast.C:1719
- [x] dyninstAPI/src/codegen.C:639
- [x] dyninstAPI/src/mapped_object.C:909
- [x] dyninstAPI/src/mapped_object.C:912
- [ ] dyninstAPI/src/inst-x86.C:1834
- [ ] dyninstAPI/src/inst-x86.C:1875 
- [x] dyninstAPI/src/inst-x86.C:1811
- [x] dyninstAPI/src/inst-x86.C:1851
- [x] dyninstAPI/src/emit-x86.C:2233
- [x] dyninstAPI/src/emit-x86.C:2240

@mxz297 @sashanicolas 

Until we switch to using C++17, there isn't a compiler-agnostic method of making a switch statement fall through without a warning. I can cook up a quick macro to handle the gcc/clang method of doing it, but I want to make sure that **all** of these are supposed to actually fall through. If we could get this in for 11.0, that would be fantastic.

### LINKED ISSUE #1080: enable more compiler warning, clean up all warning
**Intention**
When Dyninst is built, there should be not diagnostic output from the compiler.  Additional warnings should be enabled to allow the compiler to detect illegal or undefined code constructs, or potential errors that the static code analysis capabilities of the compiler can detect.  To further this effort additional warnings should be enabled.  The following set is a good starting point:

- -Wall
- -Wextra
- -Wpedantic
- -Wctor-dtor-privacy
- -Wenum-conversions
- -Wmissing-braces
- -Wmultichar
- -Walloca
- -Wcast-align
- -Wcast-qual
- -Wcomma-subscript
- -Wdeprecated-copy-dtor
- -Wdouble-promotion
- -Wduplicated-branches
- -Wduplicated-cond
- -Wextra-semi
- -Wfloat-equal
- -Wformat-overflow=2
- -Wformat-signedness
- -Wformat=2
- -Wframe-larger-than=
- -Wjump-misses-init
- -Wlogical-op
- -Wmismatched-tags
- -Wnoexcept
- -Wnon-virtual-dtor
- -Woverloaded-virtual
- -Wpointer-arith
- -Wrange-loop-construct
- -Wrestrict
- -Wshadow
- -Wsuggest-attribute=format
- -Wsuggest-attribute=malloc
- -Wstrict-null-sentinel
- -Wuninitialized
- -Wvla
- -Wvolatile
- -Wwrite-strings

**Describe the bug**
Dyninst disables several types of warnings and does not enable the entire set of warnings above.

**To Reproduce**
Build dyninst.

**Expected behavior**
The build of dyninst should produce no diagnostic output as the code should be modified to eliminate the diagnostic message.

**System (please complete the following information):**
 - All platforms
 - All versions of gcc from 6 to 11
 - Debug and Release build types

### LINKED ISSUE #1081: Make code compatible with C++14, C++17, C++20 and C11
**Intention**
Make Dyninst successfully build without warnings for all current language dialects of C and C++.

**Describe the bug**
Dyninst is only tested against C99 and C++11 currently.  It fails to build with C++20 due to STL changes and many additional diagnostics are issued due languages changes and deprecated functionality.

**To Reproduce**
Set the language standard in cmake/LanguageStandards.cmake and build.

**Expected behavior**
The code should successfully build without any diagnostic output.

**System (please complete the following information):**
 - all versions of gcc that fully support the language standard
 - all platforms

### PR DESCRIPTION
**Pull request by kupsch**
This is a large patch to clean up the Dyninst code base.  Much of this was achieved by enabling additional compiler warning (and removing the disabling of compiler warnings), and then fixing the code so diagnostic message is produced.  This work also make the code C++20 compatible. Besides the language standards the Dyninst uses currently, C++11 and C99, warning were also eliminate when specifying the following language standards C++14, C++17, C++20 and C11. The code builds cleanly with gcc 6 to 11, with optimization levels -O0, -O1, -O2, -Og and -O3 (except one warning with gcc 11).

The enabled warnings are based on compiler support for the warning by testing at build configuration time.

The code has been tested to build cleanly and run on all platforms.

Fixes #1080
Fixes #1081
Fixes #986
Fixes #818
Partial #1054

### CODE REVIEW

**Comment by hainest** [comment]
@kupsch Could you check off the items in #1054 that this fixes? Does this fix all of the implicit fallthroughs?

**Comment by kupsch** [comment]
This does fix all implicit fallthroughs.  #1054 has been updated.

**Comment by woodard** [comment]
I don't mean to add additional work for you but if you want to build on this work, it may be interesting to also try -fanalyze just to see if you can find a bunch more latent issues. https://gcc.gnu.org/onlinedocs/gcc-10.1.0/gcc/Static-Analyzer-Options.html We have found it useful here exposing latent bugs.

**Comment by hainest** [comment]
https://bottle.cs.wisc.edu/search?since_date=2021-08-03

No warnings and no regressions. We're good to go when you are ready.

**Comment by hainest** [comment]
> I don't mean to add additional work for you but if you want to build on this work, it may be interesting to also try -fanalyze just to see if you can find a bunch more latent issues. https://gcc.gnu.org/onlinedocs/gcc-10.1.0/gcc/Static-Analyzer-Options.html We have found it useful here exposing latent bugs.

Oh, yes. Static analysis is a big part of the additional testing that I want to do.

**Pull request merged**
