### PR TITLE
Fix unhandled enum values for Intel GPUs

### LINKED ISSUE #953: Unhandled enum values for Intel GPUs
@Jokeren 

We'll want to get these cleaned up for the 11.0 release.

dyninst/src/common/src/dyn_regs.C:380
	enumeration value ‘Arch_intelGen9’ not handled in switch 

dyninst/src/common/src/dyn_regs.C:407
	enumeration value ‘Arch_intelGen9’ not handled in switch 
	
dyninst/src/proccontrol/src/process.C:1929
	enumeration value ‘Arch_intelGen9’ not handled in switch 

dyninst/src/parseAPI/src/SymbolicExpression.C:369
	enumeration value ‘Arch_intelGen9’ not handled in switch

### PR DESCRIPTION
**Pull request by Jokeren**
Fixes #953

### CODE REVIEW

**Comment by hainest** [comment]
Looks good. I'll run it through our usually testing battery, but I expect no troubles. Thanks for the quick fix, Keren!

**Comment by hainest** [comment]
@Jokeren Could you rebase this on the current HEAD?

**Comment by Jokeren** [comment]
@hainest Done

**Comment by hainest** [comment]
https://bottle.cs.wisc.edu/search?dyninst_branch=PR955

LGTM. @Jokeren @mxz297 Were you able to resolve the [`getPC`](https://github.com/dyninst/dyninst/issues/953#issuecomment-770155914) question? Do we need to wait for that to be resolved before merging this?

**Comment by Jokeren** [comment]
It should be good to go. AFAIK, We don't actually rely on getPC for cuda and intel gpu instructions.

**Pull request merged**
