### PR TITLE
Updates TLS descriptors values in .dynamic section

### PR DESCRIPTION
**Pull request by sashanicolas**
when .got and .plt offsets are modified for ARMv8.

### CODE REVIEW

**Comment by hainest** [comment]
Is this independent of #612 and #614?

**Comment by mxz297** [comment]
@sashanicolas This is the issue that prevents the ARM rewriter test from passing? Or there are more issues to deal with?

**Comment by hainest** [comment]
This depends on #612.

**Comment by sashanicolas** [comment]
@mxz297 Two issues were preventing ARM rewriter inital implementation (https://github.com/dyninst/dyninst/pull/612) to work: this here (TLS descriptors) and the overlapping headers (https://github.com/dyninst/dyninst/pull/618)

**Comment by hainest** [comment]
https://bottle.cs.wisc.edu/branch/PR614

No regressions. The one on x86 is spurious (the status changed from CRASHED to FAILED).

**Pull request merged**
