### PR TITLE
Rewriter fixes, instruction decoding fixes.

### PR DESCRIPTION
**Pull request by jdetter**
Includes the fix for #96. This also contains several fixes for instruction decoding.

This also includes the `ia32_decode` cleanup. Error checking has been improved. Decoding functions can be called individually have return values to check for decoding errors. Arguments to decoding functions have been cleaned up.

All 64 bit tests are passing. All 32 bit tests pass on Windows. The 32 bit test failures are on both VEX and master, so this will not introduce any new issues.

### CODE REVIEW

**Comment by jdetter** [comment]
@mxz297 could you check to see if the latest VEX compiles on 32 bit Windows?

**Comment by pefoley2** [comment]
I found at least one build failure on windows: https://github.com/dyninst/dyninst/pull/108
The build is still running, so there may be more fixes incoming.

**Comment by pefoley2** [comment]
Looks like the vex branch builds successfully under VS2015 with the above PR.

**Comment by jdetter** [comment]
This pull request now includes #108

**Pull request merged**
