### PR TITLE
Enhance Symtab debugging support

### PR DESCRIPTION
**Pull request by jmellorcrummey**
This pull request includes enhanced debugging support that I developed to work with CUBINs, though it has nothing to do with CUBINs per se. This pull request includes

- indented dumping of IBS trees
- function range dump in Symtab
- module range dump in Symtab
- line map dump in LineInformation

### CODE REVIEW

**Comment by jmellorcrummey** [comment]
Travis:

- The build succeeded for gcc. 
- The clang build failed with the error "gcc with GNU99 support required". This is unrelated to my changes.

Appveyor:

- The build failed because it couldn't find "elfutils/libdw.h". Again, this is unrelated to my changes.

I don't know why it didn't try to test with Jenkins.

**Comment by wrwilliams** [comment]
ok to test

(One of us admin types needs to say the magic words above to get jenkins to run for non-project-members.)

**Comment by jmellorcrummey** [comment]
I downloaded the Dyninst testsuite and ran it against the changes included in this pull request. All tests pass on Linux x86, my development platform.

**Comment by sashanicolas** [comment]
rebased to master

**Pull request closed without merging**
