### PR TITLE
Add a ParseAPI::Block constructor to allow external parsers to set correctly block end address

### PR DESCRIPTION
**Pull request by mxz297**

### CODE REVIEW

**Comment by mxz297** [comment]
@hainest Ready to test.

**Comment by hainest** [comment]
@mxz297 Could you also update the ParseAPI documentation?

**Comment by hainest** [comment]
https://bottle.cs.wisc.edu/search?dyninst_branch=PR1011

Testing looks good.

**Comment by mxz297** [comment]
@hainest It is awkward that there is no mention of ParseAPI::Block constructors in the ParseAPI documentation...

**Comment by mxz297** [comment]
@hainest I pushed a commit that documents the block constructors. I did not recompile the PDF. Can you proof-read it and update the PDF file?

**Comment by hainest** [comment]
LGTM. Since we're so close to a release, I'll wait to generate the PDFs until then.

**Pull request merged**
