### PR TITLE
Adding Dockerfile to make Dyninst easier/faster to develop with

### PR DESCRIPTION
**Pull request by vsoch**
Hi Dyninst! I thought it would be useful to have a Dockerfile alongside the repository that makes it easier to develop Dyninst. Instructions and detail are added to the README in this pull request, and let me know if you have any questions.

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by vsoch** [comment]
Just a quick note - I'm working on figuring out a good development workflow after I have the container (this is my first time using spack in this way) so I'll update the PR when I document it!

**Comment by vsoch** [comment]
Okay - Dockerfile and README are updated with the full development workflow that seems to work! This could be extended to point to a quick start guide to show the user a basic CMakeLists.txt (or other setup) but probably for a seasoned Dyninst developer, the most likely user of this, that isn't necessary.

**Comment by hainest** [comment]
We have plans to eventually distribute Dyninst through Docker, but we don't want to intermix that effort here. We have a dockerhub repo (https://hub.docker.com/orgs/dyninst/repositories), but it's currently empty. It looks like the Dockerfile you have here would be the Ubuntu-21.04 version. I think that's as good a place as any to start. We'd like to support the LTS Ubuntus since 18.04 both natively and with spack-- this isn't always feasible because of our dependency minimum versions. Does dockerhub have a PR mechanism?

**Comment by vsoch** [comment]
Docker Hub does not - but I would recommend an automated deployment from a repository on GitHub to a registry. I’d also suggest using a different registry since Docker hub has rate limiting and has toyed with image purging. Would you like me to PR to the other repository with a CI recipe to employ to GitHub packages? And you could push to Docker Hub too if you like, given some brave soul has offered their credential in he environment.

**Comment by hainest** [comment]
Will be replaced by https://github.com/researchapps/dyninst-container

**Pull request closed without merging**
