### PR TITLE
Parallel DWARF parsing and improved parallel code parsing

### PR DESCRIPTION
**Pull request by mxz297**
This PR will add parallel DWARF parsing to Dyninst and improve existing parallel code parsing by reducing mutual exclusions and improving load balancing among threads.

This PR relies on the acceptance of the thread-safe libdw patch overseen by Redhat. We can use this branch for testing (https://github.com/blue42u/elfutils/tree/parallel-pr-v2).

### CODE REVIEW

**Comment by mxz297** [comment]
@hainest I feel this PR is too complicated for the typical rebase & squash style of merging. When it is ready, I would recommend that we should just click the "Merge pull request" button.

**Comment by mxz297** [comment]
This PR will resolve #327 .

**Comment by hainest** [comment]
Could someone rebase this onto the current HEAD of master?

**Comment by mxz297** [comment]
@hainest I am a little bit confused here. So, the github web interface shows that there is only one small conflict. But when I tried to resolve the conflict in command line, git shows more conflicts....

So, I decided to use the github web interface to resolve the conflict. We will see how this goes.

**Comment by hainest** [comment]
>So, I decided to use the github web interface to resolve the conflict. We will see how this goes.

>EDIT: Never mind. I probably pulled from a wrong fork.

I just pulled it, and it's now up-to-date with the current master. Thanks!

**Comment by hainest** [comment]
https://bottle.cs.wisc.edu/search?dyninst_pr=PR651&testsuite_pr=141&since_date=2020-01-10&status=OK

Passing on all platforms (modulo known regressions).

**Pull request merged**
